[package]
name = "ontopolis-world"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ontopolis-types = { workspace = true }
ontopolis-core = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
