[package]
name = "ontopolis-observer-wire"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ontopolis-types = { workspace = true }
ontopolis-observer-api = { workspace = true }
protobuf = { workspace = true }

[dev-dependencies]
