[package]
name = "ontopolis-domains"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ontopolis-types = { workspace = true }
ontopolis-core = { workspace = true }
ontopolis-world = { workspace = true }
ontopolis-biology = { workspace = true }
ontopolis-cognition = { workspace = true }
ontopolis-language = { workspace = true }
ontopolis-geography = { workspace = true }

[dev-dependencies]
