[package]
name = "ontopolis-observer"
version.workspace = true
description = "Ontopolis Observer Desktop Shell"
edition.workspace = true
license.workspace = true

[dependencies]
tauri = { version = "2", features = [] }
ontopolis-lab.workspace = true
ontopolis-observer-api.workspace = true
ontopolis-observer-wire.workspace = true
ontopolis-runtime.workspace = true
ontopolis-types.workspace = true
thiserror.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }
